name: Execution flow Matrix Test Action
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operation-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operation-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./01-execution-flow
        run: npm ci
      - name: Build project
        working-directory: ./01-execution-flow
        run: npm run build